### ISSUE TITLE
Can't find pwm/temp on Solus

### ISSUE THREAD

**Issue by nickelghost** [grmat/amdgpu-fancontrol#10]
Hi, I am a Solus user. There is no readme, so I just launched the bash file, but I'm getting a lot of these errors regarding pwm1_enable, pwm1, temp1_input. My card is RX590 from Sapphire.

```
setting fan mode to 1
./amdgpu-fancontrol: line 37: /sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable: No such file or directory
cat: /sys/class/drm/card0/device/hwmon/hwmon0/temp1_input: No such file or directory
current temp: 
cat: /sys/class/drm/card0/device/hwmon/hwmon0/pwm1: No such file or directory
current pwm: , requested to set pwm to 0
cat: /sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable: No such file or directory
./amdgpu-fancontrol: line 45: [: -ne: unary operator expected
./amdgpu-fancontrol: line 51: [: : integer expression expected
temp at last change was 
changing pwm to 0
./amdgpu-fancontrol: line 54: /sys/class/drm/card0/device/hwmon/hwmon0/pwm1: No such file or directory
cat: /sys/class/drm/card0/device/hwmon/hwmon0/temp1_input: No such file or directory
```

**Comment by grmat** [comment]
> Hi, I am a Solus user. There is no readme, so I just launched the bash file

https://github.com/grmat/amdgpu-fancontrol/blob/master/README.md

It's an example and not meant to be just ran. As it doesn't do any kind of device enumeration or udev stuff, the necessary action is documented in the script:

> # hwmon paths, hardcoded for one amdgpu card at hwmon0, adjust as needed
