### ISSUE TITLE
Doesn't interpolate between last two TEMP / PWM pairs

### ISSUE THREAD

**Issue by CuthredOreilly** [grmat/amdgpu-fancontrol#13]
There's a minor logic error in the if tests within the interpolate_pwm function.
The test for whether we've hit the final point in the list should additionally test whether the current temperature is greater than or equal to the final temperature in the list.  Without this additional test we never get to set interpolated PWM values between the 'final but one' and final points; instead the final PWM value is set as soon as the temperature exceeds the 'final but one' temperature in the list.
My scripting is poor but change:

`  for i in "${!TEMPS[@]}"; do
    if [[ $i -eq $((${#TEMPS[@]}-1)) ]]; then
      # hit last point in list, set to max speed
      set_pwm "${PWMS[i]}"
      return
...
`
to something like

`  for i in "${!TEMPS[@]}"; do
    if [[ $i -eq $((${#TEMPS[@]}-1)) ]]; then
      if [[ $TEMP -ge ${TEMPS[$i]} ]]; then
        # hit last point in list, set to max speed
        set_pwm "${PWMS[i]}"
        return
      fi
...
`
and it works a treat.

**Comment by aufkrawall** [comment]
@CuthredOreilly Could you provide the adjustment in an unambiguous formatting? It's not clear to me how to actually adjust the script while maintaining a functioning state.

@grmat I briefly have access to a different system with an MSI 5700 XT card, which has way more powerful cooling than my RX 570. With the former card I probably can confirm @CuthredOreilly findings: Instead of maintaining rpm due to hysteresis, the script falls back to the next lower step defined, which results in a constant switching of defined states by just temperature changes of 1°C.

**Comment by CuthredOreilly** [comment]
@aufkrawall I'll try. I can't get code-formatting to work correctly here so I've attached a version of amdgpu-fancontrol with my mod:

[amdgpu-fancontrol.txt](https://github.com/grmat/amdgpu-fancontrol/files/4007051/amdgpu-fancontrol.txt)

Note that I'm no longer using amdgpu-fancontrol - I now have my gpu fans plugged into a motherboard fan-header so that I can use the kubuntu supplied fancontrol for all case fans.

**Comment by aufkrawall** [comment]
Thanks a lot! The differences are:

added line 85: `if [[ $TEMP -ge ${TEMPS[$i]} ]]; then`
added line 89: `fi`

```
function interpolate_pwm {
  i=0
  TEMP=$(cat $FILE_TEMP)

  debug "current temp: $TEMP"

  if [[ $TEMP -le ${TEMPS[0]} ]]; then
    # below first point in list, set to min speed
    set_pwm "${PWMS[i]}"
    return
  fi

  for i in "${!TEMPS[@]}"; do
    if [[ $i -eq $((${#TEMPS[@]}-1)) ]]; then
     if [[ $TEMP -ge ${TEMPS[$i]} ]]; then
      # hit last point in list, set to max speed
      set_pwm "${PWMS[i]}"
      return
      fi
    elif [[ $TEMP -gt ${TEMPS[$i]} ]]; then
      continue
    fi

    # interpolate linearly
    LOWERTEMP=${TEMPS[i-1]}
    HIGHERTEMP=${TEMPS[i]}
    LOWERPWM=${PWMS[i-1]}
    HIGHERPWM=${PWMS[i]}
    PWM=$(echo "( ( $TEMP - $LOWERTEMP ) * ( $HIGHERPWM - $LOWERPWM ) / ( $HIGHERTEMP - $LOWERTEMP ) ) + $LOWERPWM" | bc)
    debug "interpolated pwm value for temperature $TEMP is: $PWM"
    set_pwm "$PWM"
    return
  done
}
```

As far as I can tell until now, it works flawlessly with my Polaris card and just three points defined. I actually had to define more points previously to get to a satisfying result.

**Comment by grmat** [comment]
Thanks. I've simplified the corresponding part, I think it should work now as expected

**Comment by aufkrawall** [comment]
Thanks!

Probably independent from that change, I'm not sure if the hysteresis is working correctly with each interpolated value. e.g. I use
```
TEMPS=( 65000  90000 )
PWMS=(     81    190 )
```
and when the GPU falls back from 79°C to just 78°C, each time the rpm value slightly decreases too. But then again it works for other values. It's set to default of `HYSTERESIS=6000`.

**Comment by grmat** [comment]
Hysteresis implementation is quite simple/naive. Feel free to run the script with `DEBUG=true` and open another issue if you think it's not behaving correctly
