### ISSUE TITLE
a bash script is good but how to install the service file in systemd ?

### ISSUE THREAD

**Issue by Azaretdodo** [grmat/amdgpu-fancontrol#24]
Hello,

a bash script is good but how to install the service file in systemd ?

for launch the script it is ok,

thank you in advance to help me install your GitHub in systemd program service manager,

Regards.

azaretdodo.

**Comment by grmat** [comment]
Hi,

depends on how you want to install it. Please check the manpage for systemd.unit(5), it list's the system and user unit search paths.

Example if you want to install it manually as a system unit (as root):

- put `amdgpu-fancontrol` in `/bin/`
- put `etc-amdgpu-fancontrol.cfg` in `/etc/amdgpu-fancontrol.cfg`
- put  `amdgpu-fancontrol.service` into `/etc/systemd/system/`
- `systemctl daemon-reload`
- `systemctl enable --now amdgpu-fancontrol.service`

**Comment by Azaretdodo** [comment]
Hello,


I have bad new,

Systemd can't start or enable your service,

How can I install your program?

Command line always crash too for start or status...

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by grmat** [comment]
Have you checked the manpage?

What is the actual issue? Post the relevant output.

**Comment by Azaretdodo** [comment]
I happening your service aren't exist,

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Azaretdodo** [comment]
I went to create the system.control folder under etc/systemd/ where I have put the service file

How can I read a log systemd for checked why systemd doesn't install your service?

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Rfvgyhn** [comment]
Not sure if this is the same issue, but my service also fails to start on boot. 

```
λ systemctl status amdgpu-fancontrol.service
● amdgpu-fancontrol.service - amdgpu-fancontrol
     Loaded: loaded (/usr/lib/systemd/system/amdgpu-fancontrol.service; enabled; vendor preset: dis>
     Active: failed (Result: exit-code) since Tue 2020-04-07 18:56:54 MDT; 33s ago
    Process: 715 ExecStart=/usr/bin/amdgpu-fancontrol (code=exited, status=1/FAILURE)
   Main PID: 715 (code=exited, status=1/FAILURE)

Apr 07 18:56:54 arch systemd[1]: Started amdgpu-fancontrol.
Apr 07 18:56:54 arch amdgpu-fancontrol[715]: invalid hwmon files
Apr 07 18:56:54 arch systemd[1]: amdgpu-fancontrol.service: Main process exited, code=exited, statu>
Apr 07 18:56:54 arch systemd[1]: amdgpu-fancontrol.service: Failed with result 'exit-code'.
```

It runs fine when I manually start the service though. 
OS: Arch
Kernel: 5.6.2-arch1-2
GPU: RX 5700 Reference
Package: https://aur.archlinux.org/packages/amdgpu-fancontrol-git/

**Comment by Azaretdodo** [comment]
I think I will add the bash script in init.d working

I will ask to systemd how to add and run the script

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Azaretdodo** [comment]
hello,


the service is working now :) 

![image](https://user-images.githubusercontent.com/30596513/78971364-addcb200-7b0b-11ea-87eb-b5ba1844ea35.png)

you can close the ticket,

Regards.


Azaretdodo
